apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: cesieats-services
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: kilme/order-service:$IMAGE_VERSION
          resources:
            limits:
              memory: "512Mi"
              cpu: "250m"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: service-order
  namespace: cesieats-services
spec:
  selector:
    app: order-service
  ports:
    - name: http
      protocol: TCP
      port: 3000
      nodePort: 30103
  type: NodePort